version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: example-6-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - velociraptor
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example-6-server
    volumes:
      - ./log.txt:/var/www/log.txt
    networks:
      - velociraptor

networks:
  velociraptor:
    driver: bridge
